### ISSUE TITLE
ScreenShare is failing

### ISSUE THREAD

**Issue by amangupta26** [Temasys/SkylinkJS#199]
on calling screenShare() method following error is thrown:
`
Error: Failed retrieving selected screen
    at chromeCallback (https://cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/skylink.complete.min.js:5:27216)
    at onIFrameCallback (https://cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/skylink.complete.min.js:5:28230)`

**Comment by johache** [comment]
Hi,
I just had a quick look at AJS. This error just means any error that is not a permission denied.

- Do you have the chrome extension installed ? (yes I guess, just double checking)
- Did you see the screen/window selection popup ?
- are you on a https website, or on localhost ?

**Comment by amangupta26** [comment]
Geez, I had chrome extension disabled. Sorry, for the inconvenience and time.
